### ISSUE TITLE
child is always associated in get_value even if requested section is missing

### ISSUE THREAD

**Issue by lewisfish** [toml-f/toml-f#110]
Hi,
Using the [Accessing nested tables](https://toml-f.readthedocs.io/en/latest/how-to/table/#accessing-nested-tables) tutorial as a base, I'm trying to understand how call get_value child variable works when the requested section is missing. 
When editing the example toml file for the above tutorial to rename the hamiltonian section to something else (eg. [foobar.dftb]) the code runs with out displaying the expected error message "No hamiltonian section found in input file". Is there a bug in get_value and child is always associated? Or am I just misunderstaning how the tutorial code works?

**Comment by awvwgk** [comment]
The `get_value` interface will eagerly create missing child tables in the root table unless the `requested=.false.` option is provided. In this (default) case the child table is only not associated if the key is associated with something else than a table, like

```toml
hamiltonian = "dftb"

[analysis]
calculate-forces = true
```

The `get_value` interface can distinguish between success (table present or table created) and failure (non-table value) by association status in this case.

If `requested=.false.` is set as for the second part of the recipe, the child pointer will only be associated to a table if it was previously present. Note that this will fail with a non-zero stat value for the provided example

```toml
analysis = ["calculate-forces"]

[hamiltonian.dftb]
scc = {}
skf.format = "mio-1-1/{}-{}.skf"
```

In this case the child pointer will be unassociated as well, however we have three possible states, success and pointer associated (table present), success and pointer unassociated (table absent) and failure and pointer unassociated (non-table value).

---

If this explanation helps I can incorporate it with the recipe in the docs.

**Comment by lewisfish** [comment]
Thanks for your quick reply! That clears things up for me. Thanks for your help!
