### ISSUE TITLE
Changes implemented in toml-f 0.3.1 compare with 0.2.4 results in FPM tests fail

### ISSUE THREAD

**Issue by band-a-prend** [toml-f/toml-f#114]
Build of [FPM](https://github.com/fortran-lang/fpm) with `toml-f 0.3.1` instead of `toml-f 0.2.4` results in FPM tests fail.

For more details please refer issue: https://github.com/fortran-lang/fpm/issues/805.

**Comment by awvwgk** [comment]
Thanks, I just checked, the issues is how fpm uses the build interface to set strings in the unit tests. There was an edge case in TOML Fortran 0.2.0 which made it necessary / possible to set the raw value of an entry directly, but this has been fixed now.

Will fix it in https://github.com/fortran-lang/fpm/pull/806.
