### ISSUE TITLE
Alternatives to ieee_value for creating exceptional values

### ISSUE THREAD

**Issue by barracuda156** [toml-f/toml-f#132]
As @awvwgk advised, opening the issue here. Original topic: https://github.com/fortran-lang/fpm/issues/882

Summary of the problem: `ieee_arithmetic` is not universally supported in `gfortran`, so using it unconditionally makes it impossible to build on certain platforms.
If it can be substituted without losing functionality, it is perhaps desirable to do so for the sake of better compatibility.

**Comment by awvwgk** [comment]
The `ieee_value` function is used to create values for `NaN`, `Inf` and `-Inf` at

https://github.com/toml-f/toml-f/blob/6290b0bc5f5ebeff231625a3b6685de85f33fc79/src/tomlf/de/lexer.f90#L1297-L1309

If there is a standard conforming way to implement these without `ieee_value` I'm happy to use those.

**Comment by awvwgk** [comment]
One quick hack would be to replace the values with BOZ literals. But this might actually be less portable, since it does not account for endianess.

```f90
 if (match(lexer, first, "n")) then 
    val = real(z'7FF8000000000001', tfr)
    return 
 end if 
  
 if (match(lexer, first, "i")) then 
    if (match(lexer, token%first, char_kind%minus)) then 
       val = real(z'FFF0000000000000', tfr)
    else 
       val = real(z'7FF0000000000000', tfr)
    end if 
    return 
 end if 
```

**Comment by barracuda156** [comment]
@awvwgk Unfortunately I cannot come up with any suggestions as long as Fortran goes. (C++ has implementations for those.)

Using code which does not account for endianness would be a step backward IMO. That will break more platforms than we have broken now :)
To be clear, I am actually looking for a generally optimal solution here, not for a hack to make it work for me. _For me_ it works, I have an experimental fix for gfortran which allows building `ieee_arithmetic` module. (The error I quoted is from Rosetta system; the same version of `fpm` builds fine on my PowerMac with kinda-fixed gfortran.)

**Comment by awvwgk** [comment]
At least `gfortran` will create errors in case one tries to use the tricks described in the C++ docs to create exceptional values: 
```
❯ cat exceptional.f90
program exceptional
  implicit none

  print '(g0)', &
    acos(2.0), &
    log(-1.0), &
    sqrt(-1.0)

  print '(g0)', &
    huge(1.0)*2
end program exceptional
❯ gfortran exceptional.f90&& ./a.out
exceptional.f90:5:9:

    5 |     acos(2.0), &
      |         1
Error: Argument of ACOS at (1) must be between -1 and 1
exceptional.f90:6:8:

    6 |     log(-1.0), &
      |        1
Error: Argument of LOG at (1) cannot be less than or equal to zero
exceptional.f90:7:9:

    7 |     sqrt(-1.0)
      |         1
Error: Argument of SQRT at (1) has a negative value
exceptional.f90:10:8:

   10 |     huge(1.0)*2
      |        1
Error: Arithmetic overflow at (1)
```

**Comment by awvwgk** [comment]
Currently I cannot come up with a better solution other than `ieee_value` which is the standard conforming way to obtain those values (in Fortran there is usually one way and only one way to archive most things).

**Comment by awvwgk** [comment]
The only more general fix I can come up with is an internal read, which I am actually trying to avoid in this piece of the code...

```f90
 if (match(lexer, first, "n")) then 
    read("NaN", *) val
    return 
 end if 
  
 if (match(lexer, first, "i")) then 
    read("Inf", *) val
    if (match(lexer, token%first, char_kind%minus)) then 
       val = -val
    end if 
    return 
 end if 
```

**Comment by barracuda156** [comment]
> The only more general fix I can come up with is an internal read, which I am actually trying to avoid in this piece of the code...
> 
> ```fortran-modern
>  if (match(lexer, first, "n")) then 
>     read("NaN", *) val
>     return 
>  end if 
>   
>  if (match(lexer, first, "i")) then 
>     read("Inf", *) val
>     if (match(lexer, token%first, char_kind%minus)) then 
>        val = -val
>     end if 
>     return 
>  end if 
> ```

Is the fallback code feasible or too complicated? Some macro that gonna determine if `ieee_arithmetic` is supported by the compiler, if not, then use suboptimal, but still working code.

**Comment by awvwgk** [comment]
While a somewhat unsatisfying solution, it seems to pass the TOML testsuite. Aince those branches are only relevant for reading exceptional values they are possibly not performance critical, so this should be an okay-ish solution for the time being.

**Comment by barracuda156** [comment]
@awvwgk Thank you!

**Comment by barracuda156** [comment]
@awvwgk Turned out, there are more instances:
```
/opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_toml-f/toml-f/work/build/_deps/test-drive-src/test/test_select.F90:15:20:

   15 |   use, intrinsic :: ieee_arithmetic, only : ieee_value, ieee_quiet_nan
      |                    1
Fatal Error: Cannot find an intrinsic module named 'ieee_arithmetic' at (1)
compilation terminated.
/opt/local/var/macports/build/_opt_PPCRosettaPorts_fortran_toml-f/toml-f/work/build/_deps/test-drive-src/test/test_check.F90:25:20:

   25 |   use, intrinsic :: ieee_arithmetic, only : ieee_value, ieee_quiet_nan
      |                    1
```

**Comment by awvwgk** [comment]
I know, I only removed cases in the library and not the tests.

**Comment by awvwgk** [comment]
I know, I only removed cases in the library and not the tests.

**Comment by barracuda156** [comment]
> I know, I only removed cases in the library and not the tests.

Got it, thanks. Maybe add an option to build without tests then? Now it is unconditional:
```
# add the testsuite
enable_testing()
set(fpm-toml "${PROJECT_SOURCE_DIR}/fpm.toml")
add_subdirectory("test")
```
