### ISSUE TITLE
Error using meson system setup

### ISSUE THREAD

**Issue by dmr-dj** [toml-f/toml-f#42]
The recommended install (as described in the HowTo) through meson does not work with the following error:

> The Meson build system
> Version: 0.53.2
> Source dir: /home/roche/toml-f
> Build dir: /home/roche/toml-f/_build
> Build type: native build
> Project name: toml-f
> Project version: 0.2.2
> Fortran compiler for the host machine: gfortran (gcc 9.3.0 "GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
> Fortran linker for the host machine: gfortran ld.bfd 2.34
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Program config/install-mod.py found: YES (/usr/bin/env python /home/roche/toml-f/config/install-mod.py)
> 
> meson.build:63:8: ERROR: add_install_script args must be strings
> 
> A full log can be found at /home/roche/toml-f/_build/meson-logs/meson-log.txt

The building process work as expected when using CMake. 
Best wishes,
dmr
[meson-log.txt](https://github.com/toml-f/toml-f/files/6878255/meson-log.txt)

[Edit: I attach the full log for reference]

**Comment by awvwgk** [comment]
Thanks for reporting, seems like I have to bump the required meson version to 0.55, that's unfortunate.

**Comment by awvwgk** [comment]
Applying this patch might work for meson 0.53:

```diff
diff --git a/meson.build b/meson.build
index bc43632..274ea17 100644
--- a/meson.build
+++ b/meson.build
@@ -61,7 +61,7 @@ if install
 
   module_id = meson.project_name() / fc_id + '-' + fc.version()
   meson.add_install_script(
-    find_program(files('config'/'install-mod.py')),
+    find_program(meson.current_source_dir()/'config'/'install-mod.py'),
     get_option('includedir') / module_id,
   )
 
```

**Comment by dmr-dj** [comment]
Excellent, this works using:
> meson setup _build
> meson test -C _build --print-errorlogs

I do not know anything about meson, but the suggested command (in HowTo):
> meson compile -C _build
does not work with error message:
> meson: error: unrecognized arguments: -C _build

Thanks already for the fix!

**Comment by awvwgk** [comment]
Ah, `meson compile` was added in 0.54 (https://mesonbuild.com/Commands.html#compile). You can use `ninja -C _build` instead.

**Comment by dmr-dj** [comment]
Perfect, thanks a lot!
Best wishes,
dmr
