### ISSUE TITLE
Nagfor: problem to compile sort.f90

### ISSUE THREAD

**Issue by aradi** [toml-f/toml-f#49]
Unfortunately, the NAG compiler can not compile toml-f, as it does not like the procedure pointer assignment in the pure `sort_keys` subroutine in sort.F90. I think, it is a compiler bug, and I've reported it already to NAG. However, it would be nice to have a quick workaround to enable testing with NAG for DFTB+ with tblite included.

Possible workarounds:
* Leave away the `pure` attribute from `sort_keys`
* Leave away the pointer assignment and put directly the `quicksort()` into the two branches of the if.

Thanks!

**Comment by awvwgk** [comment]
Removing `pure` will change the API, I prefer to keep API breakage at minimum even in pre 1.0 stage, especially for workarounds. I'm open to accept a patch for the second option, though.

**Comment by aradi** [comment]
Sure, makes sense, see #50
