### ISSUE TITLE
Variable declaration: class type instead of derived type

### ISSUE THREAD

**Issue by interkosmos** [toml-f/toml-f#5]
When declaring variables for *toml-f*, the library expects the derived types, like `toml_table`, to be of `class` instead of `type`:

```fortran
    class(toml_table), allocatable :: table
    class(toml_table), pointer     :: child
```

Is there any reason for this? Normally, `class` is used to define dummy arguments of object references only (`this`/`self`/…), not for the declaration of object-oriented types in general. Or am I missing something?

**Comment by awvwgk** [comment]
Thanks, for the feedback. I'm happy to see someone using this project.

There is not much reasoning beyond that I just started declaring all of them as `class` to remain flexible while working on the restructuring of the library. It makes it easier to move procedures around and switch them between type bound and normal procedures or vice versa.

Most of them are probably not necessary and can be replaced with `type`, once get this library is in good shape.

**Comment by interkosmos** [comment]
Perhaps, you can refactor the declarations to comply with the [Fortran standard](https://www.ibm.com/support/knowledgecenter/SSGH4D_16.1.0/com.ibm.xlf161.aix.doc/language_ref/class.html).

**Comment by awvwgk** [comment]
Sure can do
