### ISSUE TITLE
Support creating machine readable diagnostics

### ISSUE THREAD

**Issue by awvwgk** [toml-f/toml-f#90]
Raised by Giannis @gnikit in https://fortran-lang.discourse.group/t/3949/2

> Adding an option or slightly restructuring the diagnostic message to be easily parseable via regex. The message structure is already very good, but fetching the error message via regex would be hard. A good example of that is `gfortran-11`>= with the flag `-fdiagnostic-plain-output`. Having an such option would allow for code editors to parse the output of the linter to their Diagnostics console in VS Code PROBLEMS tab.

---

The current report interface turns an index of a token to a label object

https://github.com/toml-f/toml-f/blob/225174f7a858186507e7bd08c4252918dca9dee0/src/tomlf/de/context.f90#L87-L89

And creates a diagnostic object from it

https://github.com/toml-f/toml-f/blob/225174f7a858186507e7bd08c4252918dca9dee0/src/tomlf/de/context.f90#L92-L96

For the human facing output this is than turned into a string at

https://github.com/toml-f/toml-f/blob/225174f7a858186507e7bd08c4252918dca9dee0/src/tomlf/de/context.f90#L101

Note that the actual source code is only needed when creating the report string, the diagnostic object itself contains only position information from the label objects as well as the messages to display.

---

To support this without much effort on the user side, we could add a state in the context objects which describes whether the report should be optimized for humans or machines, default to human-friendly output. A tool which wants integrate its TOML Fortran usage for error reporting with the the VS Modern Fortran Extension can provide an option or environment variable to toggle this switch in the context object and make the error output automatically accessible for the Diagnostic console in VS Code.

The actual preferred format for the VS Modern Fortran Extension has to be defined first.

**Comment by gnikit** [comment]
I think I might have been to quick to the current diagnostic message format is okay. I just whipped up a REGEX that should work with VS Code's problemmatcher https://regex101.com/r/q6duAL/4 and in any other tool that uses ECMAScript (Javascript) flavour for regex

**Comment by gnikit** [comment]
The online limitation that I can think of with the current output format, is that the diagnostics are multiline and not all code editors/ linter plugins are able to capture multiline regexs. FYI VS Code is fine with that: https://code.visualstudio.com/Docs/editor/tasks#_defining-a-multiline-problem-matcher

**Comment by awvwgk** [comment]
> I just whipped up a REGEX that should work with VS Code's problemmatcher [regex101.com/r/q6duAL/4](https://regex101.com/r/q6duAL/4) and in any other tool that uses ECMAScript (Javascript) flavour for regex

The indent of the filename and line and column specifier is dependent on the line number, you have to match for multiple spaces there (https://regex101.com/r/9xImjz/2).

**Comment by gnikit** [comment]
If I have understood correctly, this will eventually be present in/part of `fpm`. Let me know when that happens to add the problemmatcher in the fortran-lang vscode extension.

I think this might be a good opportunity to try the new GitHub projects that span the entire organisation as opposed to the individual repos.

**Comment by awvwgk** [comment]
Seems to be not an issue which is worth addressing at the moment.
